server.port=8081
spring.application.name=auth-service

# Oracle Database Configuration
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=campuscare
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.community.dialect.OracleLegacyDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Configuration (used for system audit logging)
spring.data.mongodb.uri=mongodb://localhost:27017/campus_care

# Eureka Client Discovery configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT Configuration
campuscare.jwt.secret=9a67471ec639e248b61c36081512db485c2c77d465d3a5a40a5996cc5c290a6e
campuscare.jwt.expiration-ms=86400000

# Swagger UI properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Multipart configurations for large Excel database uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
