server.port=8082
spring.application.name=ticket-service

# Oracle Database Configuration (SQL)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=campuscare
spring.datasource.password=admin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.community.dialect.OracleLegacyDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MongoDB Configuration (NoSQL Comments, Activity feeds, Audits)
spring.data.mongodb.uri=mongodb://localhost:27017/campus_care

# Eureka Client Discovery configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# JWT Configuration (for securing ticket routes)
campuscare.jwt.secret=9a67471ec639e248b61c36081512db485c2c77d465d3a5a40a5996cc5c290a6e
campuscare.jwt.expiration-ms=86400000

# Swagger UI properties
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Support large base64 image uploads (up to 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10485760
server.tomcat.max-swallow-size=10485760
spring.codec.max-in-memory-size=10MB

server.error.include-message=always
server.error.include-stacktrace=always
